/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from './guide';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/core/src/zone/ng_zone';
import * as import10 from '../../services/event-services';
import * as import11 from '@angular/router/src/router';
import * as import12 from '../../services/api-service';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '@angular/forms/src/directives/ng_form';
import * as import16 from '@angular/forms/src/directives/control_container';
import * as import17 from '@angular/forms/src/directives/ng_control_status';
import * as import18 from '../../directives/component-handler';
import * as import19 from '@angular/core/src/linker/template_ref';
import * as import20 from '@angular/common/src/directives/ng_if';
import * as import21 from '@angular/common/src/directives/ng_style';
import * as import22 from '@angular/common/src/directives/ng_for';
import * as import23 from '@angular/core/src/linker/query_list';
import * as import24 from '@angular/core/src/linker/element_ref';
import * as import25 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import26 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import27 from '../../components/show-card/show-card';
import * as import28 from '../../components/show-card/show-card.ngfactory';
const nodeDebugInfos_Guide_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.Guide],import1.Guide,{})];
var renderType_Guide_Host:import2.RenderComponentType = (null as any);
class _View_Guide_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _Guide_0_4:import1.Guide;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_Guide_Host0,renderType_Guide_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_Guide_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('guide',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Guide0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Guide_0_4 = new import1.Guide(this.parentInjector.get(import9.NgZone),this.parentInjector.get(import10.EventService),this.parentInjector.get(import11.Router),this.parentInjector.get(import12.ApiService));
    this._appEl_0.initComponent(this._Guide_0_4,[],compView_0);
    compView_0.create(this._Guide_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.Guide) && (0 === requestNodeIndex))) { return this._Guide_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Guide_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      this.debug(0,0,0);
      if ((this.numberOfChecks === 0)) { this._Guide_0_4.ngAfterViewInit(); }
    }
  }
}
function viewFactory_Guide_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_Guide_Host === (null as any))) { (renderType_Guide_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,[],{})); }
  return new _View_Guide_Host0(viewUtils,parentInjector,declarationEl);
}
export const GuideNgFactory:import14.ComponentFactory<import1.Guide> = new import14.ComponentFactory<import1.Guide>('guide',viewFactory_Guide_Host0,import1.Guide);
const styles_Guide:any[] = [];
const nodeDebugInfos_Guide0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{searchEl: (null as any)}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import15.NgForm,
    import16.ControlContainer,
    import17.NgControlStatusGroup
  ]
  ,(null as any),{searchForm: (null as any)}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{input: (null as any)}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import18.ComponentHandler],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import19.TemplateRef,
    import20.NgIf
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import19.TemplateRef,
    import20.NgIf
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{guide: (null as any)}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import21.NgStyle],(null as any),{detail: (null as any)}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import18.ComponentHandler],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import19.TemplateRef,
    import20.NgIf
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import19.TemplateRef,
    import20.NgIf
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import19.TemplateRef,
    import20.NgIf
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import19.TemplateRef,
    import22.NgFor
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import18.ComponentHandler],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import19.TemplateRef,
    import20.NgIf
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
var renderType_Guide:import2.RenderComponentType = (null as any);
class _View_Guide0 extends import3.DebugAppView<import1.Guide> {
  _viewQuery_guide_0:import23.QueryList<any>;
  _viewQuery_searchEl_1:import23.QueryList<any>;
  _viewQuery_input_2:import23.QueryList<any>;
  _viewQuery_searchForm_3:import23.QueryList<any>;
  _viewQuery_detail_4:import23.QueryList<any>;
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _NgForm_2_3:import15.NgForm;
  _ControlContainer_2_4:any;
  _NgControlStatusGroup_2_5:import17.NgControlStatusGroup;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _ComponentHandler_6_3:import18.ComponentHandler;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _appEl_8:import4.AppElement;
  _TemplateRef_8_5:any;
  _NgIf_8_6:import20.NgIf;
  _text_9:any;
  _anchor_10:any;
  /*private*/ _appEl_10:import4.AppElement;
  _TemplateRef_10_5:any;
  _NgIf_10_6:import20.NgIf;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _NgStyle_28_3:import21.NgStyle;
  _text_29:any;
  _el_30:any;
  _ComponentHandler_30_3:import18.ComponentHandler;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _text_40:any;
  _el_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _text_53:any;
  _anchor_54:any;
  /*private*/ _appEl_54:import4.AppElement;
  _TemplateRef_54_5:any;
  _NgIf_54_6:import20.NgIf;
  _text_55:any;
  _anchor_56:any;
  /*private*/ _appEl_56:import4.AppElement;
  _TemplateRef_56_5:any;
  _NgIf_56_6:import20.NgIf;
  _text_57:any;
  _anchor_58:any;
  /*private*/ _appEl_58:import4.AppElement;
  _TemplateRef_58_5:any;
  _NgIf_58_6:import20.NgIf;
  _text_59:any;
  _text_60:any;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _anchor_66:any;
  /*private*/ _appEl_66:import4.AppElement;
  _TemplateRef_66_5:any;
  _NgFor_66_6:import22.NgFor;
  _text_67:any;
  _text_68:any;
  _el_69:any;
  _ComponentHandler_69_3:import18.ComponentHandler;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _text_73:any;
  _text_74:any;
  _anchor_75:any;
  /*private*/ _appEl_75:import4.AppElement;
  _TemplateRef_75_5:any;
  _NgIf_75_6:import20.NgIf;
  _text_76:any;
  _text_77:any;
  _text_78:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  _map_0:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_25:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_Guide0,renderType_Guide,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_Guide0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_guide_0 = new import23.QueryList<any>();
    this._viewQuery_searchEl_1 = new import23.QueryList<any>();
    this._viewQuery_input_2 = new import23.QueryList<any>();
    this._viewQuery_searchForm_3 = new import23.QueryList<any>();
    this._viewQuery_detail_4 = new import23.QueryList<any>();
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',this.debug(0,0,0));
    this.renderer.setElementAttribute(this._el_0,'class','search-container');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',this.debug(1,0,64));
    this._el_2 = this.renderer.createElement(this._el_0,'form',this.debug(2,1,2));
    this.renderer.setElementAttribute(this._el_2,'class','search-form');
    this._NgForm_2_3 = new import15.NgForm((null as any),(null as any));
    this._ControlContainer_2_4 = this._NgForm_2_3;
    this._NgControlStatusGroup_2_5 = new import17.NgControlStatusGroup(this._ControlContainer_2_4);
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',this.debug(3,1,71));
    this._el_4 = this.renderer.createElement(this._el_2,'input',this.debug(4,2,4));
    this.renderer.setElementAttribute(this._el_4,'class','search-field');
    this.renderer.setElementAttribute(this._el_4,'placeholder','Search shows...');
    this._text_5 = this.renderer.createText(this._el_2,'\n    ',this.debug(5,2,94));
    this._el_6 = this.renderer.createElement(this._el_2,'button',this.debug(6,3,4));
    this.renderer.setElementAttribute(this._el_6,'class','mdl-button mdl-js-button mdl-button--icon');
    this.renderer.setElementAttribute(this._el_6,'component-handler','');
    this.renderer.setElementAttribute(this._el_6,'type','submit');
    this._ComponentHandler_6_3 = new import18.ComponentHandler(new import24.ElementRef(this._el_6),this.renderer);
    this._text_7 = this.renderer.createText(this._el_6,'\n      ',this.debug(7,3,94));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_6,this.debug(8,4,6));
    this._appEl_8 = new import4.AppElement(8,6,this,this._anchor_8);
    this._TemplateRef_8_5 = new import19.TemplateRef_(this._appEl_8,viewFactory_Guide1);
    this._NgIf_8_6 = new import20.NgIf(this._appEl_8.vcRef,this._TemplateRef_8_5);
    this._text_9 = this.renderer.createText(this._el_6,'\n      ',this.debug(9,4,60));
    this._anchor_10 = this.renderer.createTemplateAnchor(this._el_6,this.debug(10,5,6));
    this._appEl_10 = new import4.AppElement(10,6,this,this._anchor_10);
    this._TemplateRef_10_5 = new import19.TemplateRef_(this._appEl_10,viewFactory_Guide2);
    this._NgIf_10_6 = new import20.NgIf(this._appEl_10.vcRef,this._TemplateRef_10_5);
    this._text_11 = this.renderer.createText(this._el_6,'\n    ',this.debug(11,5,60));
    this._text_12 = this.renderer.createText(this._el_2,'\n  ',this.debug(12,6,13));
    this._text_13 = this.renderer.createText(this._el_0,'\n',this.debug(13,7,9));
    this._text_14 = this.renderer.createText(parentRenderNode,'\n',this.debug(14,8,6));
    this._el_15 = this.renderer.createElement(parentRenderNode,'div',this.debug(15,9,0));
    this.renderer.setElementAttribute(this._el_15,'class','guide-container');
    this._text_16 = this.renderer.createText(this._el_15,'\n  ',this.debug(16,9,60));
    this._el_17 = this.renderer.createElement(this._el_15,'header',this.debug(17,10,2));
    this.renderer.setElementAttribute(this._el_17,'class','guide-header');
    this._text_18 = this.renderer.createText(this._el_17,'\n    ',this.debug(18,10,31));
    this._el_19 = this.renderer.createElement(this._el_17,'div',this.debug(19,11,4));
    this.renderer.setElementAttribute(this._el_19,'class','logo');
    this._text_20 = this.renderer.createText(this._el_19,'\n    ',this.debug(20,11,22));
    this._text_21 = this.renderer.createText(this._el_17,'\n    ',this.debug(21,12,10));
    this._el_22 = this.renderer.createElement(this._el_17,'span',this.debug(22,13,4));
    this.renderer.setElementAttribute(this._el_22,'class','date-time');
    this._text_23 = this.renderer.createText(this._el_22,'',this.debug(23,13,28));
    this._text_24 = this.renderer.createText(this._el_17,'\n  ',this.debug(24,13,43));
    this._text_25 = this.renderer.createText(this._el_15,'\n  ',this.debug(25,14,11));
    this._el_26 = this.renderer.createElement(this._el_15,'div',this.debug(26,15,2));
    this.renderer.setElementAttribute(this._el_26,'class','search-overlay');
    this._text_27 = this.renderer.createText(this._el_15,'\n  ',this.debug(27,15,36));
    this._el_28 = this.renderer.createElement(this._el_15,'section',this.debug(28,16,2));
    this.renderer.setElementAttribute(this._el_28,'class','guide-details');
    this._NgStyle_28_3 = new import21.NgStyle(this.parentInjector.get(import25.KeyValueDiffers),new import24.ElementRef(this._el_28),this.renderer);
    this._text_29 = this.renderer.createText(this._el_28,'\n      ',this.debug(29,19,50));
    this._el_30 = this.renderer.createElement(this._el_28,'button',this.debug(30,20,6));
    this.renderer.setElementAttribute(this._el_30,'class','mdl-button mdl-js-button mdl-button--icon back-button');
    this.renderer.setElementAttribute(this._el_30,'component-handler','');
    this._ComponentHandler_30_3 = new import18.ComponentHandler(new import24.ElementRef(this._el_30),this.renderer);
    this._text_31 = this.renderer.createText(this._el_30,'\n        ',this.debug(31,20,119));
    this._el_32 = this.renderer.createElement(this._el_30,'i',this.debug(32,21,8));
    this.renderer.setElementAttribute(this._el_32,'class','material-icons');
    this._text_33 = this.renderer.createText(this._el_32,'arrow_backward',this.debug(33,21,35));
    this._text_34 = this.renderer.createText(this._el_30,'\n      ',this.debug(34,21,53));
    this._text_35 = this.renderer.createText(this._el_28,'\n      ',this.debug(35,22,15));
    this._el_36 = this.renderer.createElement(this._el_28,'header',this.debug(36,23,6));
    this.renderer.setElementAttribute(this._el_36,'class','guide-header');
    this._text_37 = this.renderer.createText(this._el_36,'\n        ',this.debug(37,23,35));
    this._el_38 = this.renderer.createElement(this._el_36,'div',this.debug(38,24,8));
    this.renderer.setElementAttribute(this._el_38,'class','logo');
    this._text_39 = this.renderer.createText(this._el_38,'\n        ',this.debug(39,24,26));
    this._text_40 = this.renderer.createText(this._el_36,'\n        ',this.debug(40,25,14));
    this._el_41 = this.renderer.createElement(this._el_36,'span',this.debug(41,26,8));
    this.renderer.setElementAttribute(this._el_41,'class','date-time');
    this._text_42 = this.renderer.createText(this._el_41,'',this.debug(42,26,32));
    this._text_43 = this.renderer.createText(this._el_36,'\n      ',this.debug(43,26,47));
    this._text_44 = this.renderer.createText(this._el_28,'\n      ',this.debug(44,27,15));
    this._text_45 = this.renderer.createText(this._el_28,'\n      ',this.debug(45,28,81));
    this._el_46 = this.renderer.createElement(this._el_28,'div',this.debug(46,29,6));
    this.renderer.setElementAttribute(this._el_46,'class','detail-info');
    this._text_47 = this.renderer.createText(this._el_46,'\n        ',this.debug(47,29,31));
    this._el_48 = this.renderer.createElement(this._el_46,'h1',this.debug(48,30,8));
    this.renderer.setElementAttribute(this._el_48,'class','detail-name');
    this._text_49 = this.renderer.createText(this._el_48,'',this.debug(49,30,32));
    this._text_50 = this.renderer.createText(this._el_46,'\n        ',this.debug(50,32,13));
    this._el_51 = this.renderer.createElement(this._el_46,'span',this.debug(51,33,8));
    this.renderer.setElementAttribute(this._el_51,'class','detail-info-text');
    this._text_52 = this.renderer.createText(this._el_51,'',this.debug(52,33,40));
    this._text_53 = this.renderer.createText(this._el_46,'\n        ',this.debug(53,35,15));
    this._anchor_54 = this.renderer.createTemplateAnchor(this._el_46,this.debug(54,36,8));
    this._appEl_54 = new import4.AppElement(54,46,this,this._anchor_54);
    this._TemplateRef_54_5 = new import19.TemplateRef_(this._appEl_54,viewFactory_Guide3);
    this._NgIf_54_6 = new import20.NgIf(this._appEl_54.vcRef,this._TemplateRef_54_5);
    this._text_55 = this.renderer.createText(this._el_46,'\n        ',this.debug(55,38,15));
    this._anchor_56 = this.renderer.createTemplateAnchor(this._el_46,this.debug(56,39,8));
    this._appEl_56 = new import4.AppElement(56,46,this,this._anchor_56);
    this._TemplateRef_56_5 = new import19.TemplateRef_(this._appEl_56,viewFactory_Guide4);
    this._NgIf_56_6 = new import20.NgIf(this._appEl_56.vcRef,this._TemplateRef_56_5);
    this._text_57 = this.renderer.createText(this._el_46,'\n        ',this.debug(57,41,15));
    this._anchor_58 = this.renderer.createTemplateAnchor(this._el_46,this.debug(58,42,8));
    this._appEl_58 = new import4.AppElement(58,46,this,this._anchor_58);
    this._TemplateRef_58_5 = new import19.TemplateRef_(this._appEl_58,viewFactory_Guide5);
    this._NgIf_58_6 = new import20.NgIf(this._appEl_58.vcRef,this._TemplateRef_58_5);
    this._text_59 = this.renderer.createText(this._el_46,'\n\n      ',this.debug(59,52,11));
    this._text_60 = this.renderer.createText(this._el_28,'\n\n  ',this.debug(60,54,12));
    this._text_61 = this.renderer.createText(this._el_15,'\n  ',this.debug(61,56,12));
    this._el_62 = this.renderer.createElement(this._el_15,'section',this.debug(62,57,2));
    this.renderer.setElementAttribute(this._el_62,'class','guide-grid');
    this._text_63 = this.renderer.createText(this._el_62,'\n    ',this.debug(63,57,30));
    this._el_64 = this.renderer.createElement(this._el_62,'ul',this.debug(64,58,4));
    this.renderer.setElementAttribute(this._el_64,'class','guide-grid-items');
    this._text_65 = this.renderer.createText(this._el_64,'\n      ',this.debug(65,58,33));
    this._anchor_66 = this.renderer.createTemplateAnchor(this._el_64,this.debug(66,59,6));
    this._appEl_66 = new import4.AppElement(66,64,this,this._anchor_66);
    this._TemplateRef_66_5 = new import19.TemplateRef_(this._appEl_66,viewFactory_Guide6);
    this._NgFor_66_6 = new import22.NgFor(this._appEl_66.vcRef,this._TemplateRef_66_5,this.parentInjector.get(import26.IterableDiffers),this.ref);
    this._text_67 = this.renderer.createText(this._el_64,'\n    ',this.debug(67,61,11));
    this._text_68 = this.renderer.createText(this._el_62,'\n    ',this.debug(68,62,9));
    this._el_69 = this.renderer.createElement(this._el_62,'button',this.debug(69,63,4));
    this.renderer.setElementAttribute(this._el_69,'class','mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect mdl-button--colored');
    this.renderer.setElementAttribute(this._el_69,'component-handler','');
    this._ComponentHandler_69_3 = new import18.ComponentHandler(new import24.ElementRef(this._el_69),this.renderer);
    this._text_70 = this.renderer.createText(this._el_69,'\n      ',this.debug(70,63,145));
    this._el_71 = this.renderer.createElement(this._el_69,'i',this.debug(71,64,6));
    this.renderer.setElementAttribute(this._el_71,'class','material-icons');
    this._text_72 = this.renderer.createText(this._el_71,'search',this.debug(72,64,32));
    this._text_73 = this.renderer.createText(this._el_69,'\n    ',this.debug(73,64,42));
    this._text_74 = this.renderer.createText(this._el_62,'\n\n    ',this.debug(74,65,13));
    this._anchor_75 = this.renderer.createTemplateAnchor(this._el_62,this.debug(75,67,4));
    this._appEl_75 = new import4.AppElement(75,62,this,this._anchor_75);
    this._TemplateRef_75_5 = new import19.TemplateRef_(this._appEl_75,viewFactory_Guide7);
    this._NgIf_75_6 = new import20.NgIf(this._appEl_75.vcRef,this._TemplateRef_75_5);
    this._text_76 = this.renderer.createText(this._el_62,'\n  ',this.debug(76,69,13));
    this._text_77 = this.renderer.createText(this._el_15,'\n',this.debug(77,70,12));
    this._text_78 = this.renderer.createText(parentRenderNode,'\n',this.debug(78,71,6));
    this._expr_0 = import8.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_2,'submit',this.eventHandler(this._handle_submit_2_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_2,'reset',this.eventHandler(this._handle_reset_2_1.bind(this)));
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    this._expr_8 = import8.UNINITIALIZED;
    this._expr_9 = import8.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_4,'input',this.eventHandler(this._handle_input_4_0.bind(this)));
    this._expr_11 = import8.UNINITIALIZED;
    this._expr_12 = import8.UNINITIALIZED;
    this._expr_13 = import8.UNINITIALIZED;
    this._expr_14 = import8.UNINITIALIZED;
    this._map_0 = import5.pureProxy1((p0:any):{[key: string]:any} => {
      return {'background-image': p0};
    });
    this._expr_15 = import8.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_30,'click',this.eventHandler(this._handle_click_30_0.bind(this)));
    this._expr_17 = import8.UNINITIALIZED;
    this._expr_18 = import8.UNINITIALIZED;
    this._expr_19 = import8.UNINITIALIZED;
    this._expr_20 = import8.UNINITIALIZED;
    this._expr_21 = import8.UNINITIALIZED;
    this._expr_22 = import8.UNINITIALIZED;
    this._expr_23 = import8.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_69,'click',this.eventHandler(this._handle_click_69_0.bind(this)));
    this._expr_25 = import8.UNINITIALIZED;
    this._viewQuery_guide_0.reset([new import24.ElementRef(this._el_15)]);
    this.context.guide = this._viewQuery_guide_0.first;
    this._viewQuery_searchEl_1.reset([new import24.ElementRef(this._el_0)]);
    this.context.searchEl = this._viewQuery_searchEl_1.first;
    this._viewQuery_input_2.reset([new import24.ElementRef(this._el_4)]);
    this.context.input = this._viewQuery_input_2.first;
    this._viewQuery_searchForm_3.reset([new import24.ElementRef(this._el_2)]);
    this.context.searchForm = this._viewQuery_searchForm_3.first;
    this._viewQuery_detail_4.reset([new import24.ElementRef(this._el_28)]);
    this.context.detail = this._viewQuery_detail_4.first;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._anchor_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._anchor_54,
      this._text_55,
      this._anchor_56,
      this._text_57,
      this._anchor_58,
      this._text_59,
      this._text_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._anchor_66,
      this._text_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._text_73,
      this._text_74,
      this._anchor_75,
      this._text_76,
      this._text_77,
      this._text_78
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import19.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import20.NgIf) && (8 === requestNodeIndex))) { return this._NgIf_8_6; }
    if (((token === import19.TemplateRef) && (10 === requestNodeIndex))) { return this._TemplateRef_10_5; }
    if (((token === import20.NgIf) && (10 === requestNodeIndex))) { return this._NgIf_10_6; }
    if (((token === import18.ComponentHandler) && ((6 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._ComponentHandler_6_3; }
    if (((token === import15.NgForm) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NgForm_2_3; }
    if (((token === import16.ControlContainer) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._ControlContainer_2_4; }
    if (((token === import17.NgControlStatusGroup) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._NgControlStatusGroup_2_5; }
    if (((token === import18.ComponentHandler) && ((30 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._ComponentHandler_30_3; }
    if (((token === import19.TemplateRef) && (54 === requestNodeIndex))) { return this._TemplateRef_54_5; }
    if (((token === import20.NgIf) && (54 === requestNodeIndex))) { return this._NgIf_54_6; }
    if (((token === import19.TemplateRef) && (56 === requestNodeIndex))) { return this._TemplateRef_56_5; }
    if (((token === import20.NgIf) && (56 === requestNodeIndex))) { return this._NgIf_56_6; }
    if (((token === import19.TemplateRef) && (58 === requestNodeIndex))) { return this._TemplateRef_58_5; }
    if (((token === import20.NgIf) && (58 === requestNodeIndex))) { return this._NgIf_58_6; }
    if (((token === import21.NgStyle) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 60)))) { return this._NgStyle_28_3; }
    if (((token === import19.TemplateRef) && (66 === requestNodeIndex))) { return this._TemplateRef_66_5; }
    if (((token === import22.NgFor) && (66 === requestNodeIndex))) { return this._NgFor_66_6; }
    if (((token === import18.ComponentHandler) && ((69 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._ComponentHandler_69_3; }
    if (((token === import19.TemplateRef) && (75 === requestNodeIndex))) { return this._TemplateRef_75_5; }
    if (((token === import20.NgIf) && (75 === requestNodeIndex))) { return this._NgIf_75_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ComponentHandler_6_3.ngOnInit(); }
    this.debug(8,4,32);
    const currVal_11:any = this.context.searching;
    if (import5.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._NgIf_8_6.ngIf = currVal_11;
      this._expr_11 = currVal_11;
    }
    this.debug(10,5,32);
    const currVal_12:boolean = !this.context.searching;
    if (import5.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._NgIf_10_6.ngIf = currVal_12;
      this._expr_12 = currVal_12;
    }
    this.debug(28,16,41);
    const currVal_15:any = this._map_0((('radial-gradient(\n        rgba(0, 0, 0, 0),\n        rgba(0, 0, 0, 0.81)\n      ),url(' + ((this.context.selectedshow == (null as any))? (null as any): ((this.context.selectedshow.image == (null as any))? (null as any): this.context.selectedshow.image.original))) + ')'));
    if (import5.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._NgStyle_28_3.ngStyle = currVal_15;
      this._expr_15 = currVal_15;
    }
    if (!throwOnChange) { this._NgStyle_28_3.ngDoCheck(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ComponentHandler_30_3.ngOnInit(); }
    this.debug(54,36,39);
    const currVal_20:any = this.context.searchResults;
    if (import5.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this._NgIf_54_6.ngIf = currVal_20;
      this._expr_20 = currVal_20;
    }
    this.debug(56,39,39);
    const currVal_21:boolean = !this.context.searchResults;
    if (import5.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._NgIf_56_6.ngIf = currVal_21;
      this._expr_21 = currVal_21;
    }
    this.debug(58,42,33);
    const currVal_22:any = (this.context.searchResults && ((this.context.selectedshow == (null as any))? (null as any): this.context.selectedshow._embedded));
    if (import5.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this._NgIf_58_6.ngIf = currVal_22;
      this._expr_22 = currVal_22;
    }
    this.debug(66,59,6);
    changes = (null as any);
    this.debug(66,59,34);
    const currVal_23:any = this.context.shows;
    if (import5.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._NgFor_66_6.ngForOf = currVal_23;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import8.SimpleChange(this._expr_23,currVal_23);
      this._expr_23 = currVal_23;
    }
    if ((changes !== (null as any))) { this._NgFor_66_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_66_6.ngDoCheck(); }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ComponentHandler_69_3.ngOnInit(); }
    this.debug(75,67,38);
    const currVal_25:any = this.context.searchResults;
    if (import5.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this._NgIf_75_6.ngIf = currVal_25;
      this._expr_25 = currVal_25;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(0,0,30);
    const currVal_0:any = this.context.search;
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_0,'search',currVal_0);
      this._expr_0 = currVal_0;
    }
    this.debug(2,1,2);
    const currVal_4:any = this._NgControlStatusGroup_2_5.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_2,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    this.debug(2,1,2);
    const currVal_5:any = this._NgControlStatusGroup_2_5.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_2,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    this.debug(2,1,2);
    const currVal_6:any = this._NgControlStatusGroup_2_5.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_2,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    this.debug(2,1,2);
    const currVal_7:any = this._NgControlStatusGroup_2_5.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_2,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    this.debug(2,1,2);
    const currVal_8:any = this._NgControlStatusGroup_2_5.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_2,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    this.debug(2,1,2);
    const currVal_9:any = this._NgControlStatusGroup_2_5.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_2,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    this.debug(15,9,36);
    const currVal_13:any = this.context.search;
    if (import5.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_15,'search',currVal_13);
      this._expr_13 = currVal_13;
    }
    this.debug(23,13,28);
    const currVal_14:any = import5.interpolate(1,'',this.context.date,'');
    if (import5.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setText(this._text_23,currVal_14);
      this._expr_14 = currVal_14;
    }
    this.debug(42,26,32);
    const currVal_17:any = import5.interpolate(1,'',this.context.date,'');
    if (import5.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setText(this._text_42,currVal_17);
      this._expr_17 = currVal_17;
    }
    this.debug(49,30,32);
    const currVal_18:any = import5.interpolate(1,'\n          ',((this.context.selectedshow == (null as any))? (null as any): this.context.selectedshow.showname),'\n        ');
    if (import5.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setText(this._text_49,currVal_18);
      this._expr_18 = currVal_18;
    }
    this.debug(52,33,40);
    const currVal_19:any = import5.interpolate(1,'\n          ',((this.context.selectedshow == (null as any))? (null as any): this.context.selectedshow.runtime),' min\n        ');
    if (import5.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setText(this._text_52,currVal_19);
      this._expr_19 = currVal_19;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_submit_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(2,1,28);
    const pd_0:any = ((<any>this.context.search_show($event)) !== false);
    this.debug(2,1,2);
    const pd_1:any = ((<any>this._NgForm_2_3.onSubmit()) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_reset_2_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(2,1,2);
    const pd_0:any = ((<any>this._NgForm_2_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_input_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(4,2,62);
    const pd_0:any = ((<any>this.context.typing(this._el_4)) !== false);
    return (true && pd_0);
  }
  private _handle_click_30_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(30,20,14);
    const pd_0:any = ((<any>this.context.close_detail()) !== false);
    return (true && pd_0);
  }
  private _handle_click_69_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(69,63,12);
    const pd_0:any = ((<any>this.context.open_search()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_Guide0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.Guide> {
  if ((renderType_Guide === (null as any))) { (renderType_Guide = viewUtils.createRenderComponentType('/mnt/c/Users/asqwrd/Documents/GitHub/tv2/app/pages/guide/guide.html',0,import13.ViewEncapsulation.None,styles_Guide,{})); }
  return new _View_Guide0(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_Guide1:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
class _View_Guide1 extends import3.DebugAppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_Guide1,renderType_Guide,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_Guide1);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'i',this.debug(0,4,6));
    this.renderer.setElementAttribute(this._el_0,'class','material-icons');
    this._text_1 = this.renderer.createText(this._el_0,'search',this.debug(1,4,50));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_Guide1(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  return new _View_Guide1(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_Guide2:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
class _View_Guide2 extends import3.DebugAppView<any> {
  _el_0:any;
  _text_1:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_Guide2,renderType_Guide,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_Guide2);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'i',this.debug(0,5,6));
    this.renderer.setElementAttribute(this._el_0,'class','material-icons');
    this._text_1 = this.renderer.createText(this._el_0,'close',this.debug(1,5,51));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
function viewFactory_Guide2(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  return new _View_Guide2(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_Guide3:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
class _View_Guide3 extends import3.DebugAppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_Guide3,renderType_Guide,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_Guide3);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',this.debug(0,36,8));
    this.renderer.setElementAttribute(this._el_0,'class','detail-info-text');
    this._text_1 = this.renderer.createText(this._el_0,'',this.debug(1,36,61));
    this._expr_0 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(1,36,61);
    const currVal_0:any = import5.interpolate(1,'\n            | ',((this.parent.context.selectedshow == (null as any))? (null as any): this.parent.context.selectedshow.status),'\n        ');
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Guide3(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  return new _View_Guide3(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_Guide4:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
class _View_Guide4 extends import3.DebugAppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_Guide4,renderType_Guide,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_Guide4);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'span',this.debug(0,39,8));
    this.renderer.setElementAttribute(this._el_0,'class','detail-info-text');
    this._text_1 = this.renderer.createText(this._el_0,'',this.debug(1,39,62));
    this._expr_0 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(1,39,62);
    const currVal_0:any = import5.interpolate(2,'\n          | Season ',((this.parent.context.selectedshow == (null as any))? (null as any): this.parent.context.selectedshow.season),' | Episode ',((this.parent.context.selectedshow == (null as any))? (null as any): this.parent.context.selectedshow.epsnumber),'\n        ');
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Guide4(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  return new _View_Guide4(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_Guide5:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
class _View_Guide5 extends import3.DebugAppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_Guide5,renderType_Guide,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_Guide5);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ul',this.debug(0,42,8));
    this.renderer.setElementAttribute(this._el_0,'class','next-details');
    this._text_1 = this.renderer.createText(this._el_0,'\n          ',this.debug(1,42,82));
    this._el_2 = this.renderer.createElement(this._el_0,'li',this.debug(2,43,10));
    this.renderer.setElementAttribute(this._el_2,'class','next-detail');
    this._text_3 = this.renderer.createText(this._el_2,'\n            ',this.debug(3,43,34));
    this._el_4 = this.renderer.createElement(this._el_2,'span',this.debug(4,44,12));
    this.renderer.setElementAttribute(this._el_4,'class','next-label');
    this._text_5 = this.renderer.createText(this._el_4,'Next episode',this.debug(5,44,37));
    this._text_6 = this.renderer.createText(this._el_2,'',this.debug(6,44,56));
    this._text_7 = this.renderer.createText(this._el_0,'\n          ',this.debug(7,45,15));
    this._el_8 = this.renderer.createElement(this._el_0,'li',this.debug(8,46,10));
    this.renderer.setElementAttribute(this._el_8,'class','next-detail');
    this._text_9 = this.renderer.createText(this._el_8,'\n            ',this.debug(9,46,34));
    this._el_10 = this.renderer.createElement(this._el_8,'span',this.debug(10,47,12));
    this.renderer.setElementAttribute(this._el_10,'class','next-label');
    this._text_11 = this.renderer.createText(this._el_10,'Number:',this.debug(11,47,37));
    this._text_12 = this.renderer.createText(this._el_8,'',this.debug(12,47,51));
    this._text_13 = this.renderer.createText(this._el_0,'\n          ',this.debug(13,48,15));
    this._el_14 = this.renderer.createElement(this._el_0,'li',this.debug(14,49,10));
    this.renderer.setElementAttribute(this._el_14,'class','next-detail');
    this._text_15 = this.renderer.createText(this._el_14,'\n            ',this.debug(15,49,34));
    this._el_16 = this.renderer.createElement(this._el_14,'span',this.debug(16,50,12));
    this.renderer.setElementAttribute(this._el_16,'class','next-label');
    this._text_17 = this.renderer.createText(this._el_16,'Airdate:',this.debug(17,50,37));
    this._text_18 = this.renderer.createText(this._el_14,'',this.debug(18,50,52));
    this._text_19 = this.renderer.createText(this._el_0,'\n      ',this.debug(19,51,15));
    this._expr_0 = import8.UNINITIALIZED;
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(6,44,56);
    const currVal_0:any = import5.interpolate(1,' ',((this.parent.context.selectedshow == (null as any))? (null as any): this.parent.context.selectedshow._embedded.nextepisode.name),'\n          ');
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_6,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.debug(12,47,51);
    const currVal_1:any = import5.interpolate(2,'  S',((this.parent.context.selectedshow == (null as any))? (null as any): this.parent.context.selectedshow._embedded.nextepisode.season),'Ep',((this.parent.context.selectedshow == (null as any))? (null as any): this.parent.context.selectedshow._embedded.nextepisode.number),'\n          ');
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_12,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.debug(18,50,52);
    const currVal_2:any = import5.interpolate(2,' ',((this.parent.context.selectedshow == (null as any))? (null as any): this.parent.context.selectedshow._embedded.nextepisode.airdate),' ',((this.parent.context.selectedshow == (null as any))? (null as any): this.parent.context.selectedshow._embedded.nextepisode.airtime),'\n          ');
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_18,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Guide5(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  return new _View_Guide5(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_Guide6:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import27.ShowCard],import27.ShowCard,{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
class _View_Guide6 extends import3.DebugAppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import4.AppElement;
  _ShowCard_2_4:import27.ShowCard;
  _text_3:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_Guide6,renderType_Guide,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_Guide6);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',this.debug(0,59,6));
    this.renderer.setElementAttribute(this._el_0,'class','guide-grid-item');
    this._text_1 = this.renderer.createText(this._el_0,'\n        ',this.debug(1,59,89));
    this._el_2 = this.renderer.createElement(this._el_0,'show-card',this.debug(2,60,8));
    this._appEl_2 = new import4.AppElement(2,0,this,this._el_2);
    var compView_2:any = import28.viewFactory_ShowCard0(this.viewUtils,this.injector(2),this._appEl_2);
    this._ShowCard_2_4 = new import27.ShowCard();
    this._appEl_2.initComponent(this._ShowCard_2_4,[],compView_2);
    compView_2.create(this._ShowCard_2_4,[],(null as any));
    this._text_3 = this.renderer.createText(this._el_0,'\n      ',this.debug(3,60,46));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import27.ShowCard) && (2 === requestNodeIndex))) { return this._ShowCard_2_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(2,60,19);
    const currVal_1:any = this.context.$implicit;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._ShowCard_2_4.show = currVal_1;
      this._expr_1 = currVal_1;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ShowCard_2_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      this.debug(2,60,8);
      if ((this.numberOfChecks === 0)) { this._ShowCard_2_4.ngAfterViewInit(); }
    }
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(0,59,61);
    const pd_0:any = ((<any>this.parent.context.select_show(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_Guide6(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  return new _View_Guide6(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_Guide7:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([import18.ComponentHandler],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
class _View_Guide7 extends import3.DebugAppView<any> {
  _el_0:any;
  _ComponentHandler_0_3:import18.ComponentHandler;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_Guide7,renderType_Guide,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_Guide7);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'button',this.debug(0,67,4));
    this.renderer.setElementAttribute(this._el_0,'class','clear-search mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect');
    this.renderer.setElementAttribute(this._el_0,'component-handler','');
    this._ComponentHandler_0_3 = new import18.ComponentHandler(new import24.ElementRef(this._el_0),this.renderer);
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',this.debug(1,67,161));
    this._el_2 = this.renderer.createElement(this._el_0,'i',this.debug(2,68,6));
    this.renderer.setElementAttribute(this._el_2,'class','material-icons');
    this._text_3 = this.renderer.createText(this._el_2,'clear',this.debug(3,68,32));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',this.debug(4,68,41));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.ComponentHandler) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._ComponentHandler_0_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ComponentHandler_0_3.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(0,67,12);
    const pd_0:any = ((<any>this.parent.context.clear_search()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_Guide7(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  return new _View_Guide7(viewUtils,parentInjector,declarationEl);
}