/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from './layout';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '../services/api-service';
import * as import10 from '../services/event-services';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '@angular/router/src/directives/router_outlet';
import * as import13 from '@angular/router/src/router_outlet_map';
import * as import14 from '@angular/core/src/linker/component_factory_resolver';
import * as import15 from '@angular/core/src/metadata/view';
const nodeDebugInfos_Layout_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.Layout],import1.Layout,{})];
var renderType_Layout_Host:import2.RenderComponentType = null;
class _View_Layout_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  private _appEl_0:import4.AppElement;
  _Layout_0_4:import1.Layout;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_Layout_Host0,renderType_Layout_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_Layout_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('layout',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,null,this,this._el_0);
    var compView_0:any = viewFactory_Layout0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Layout_0_4 = new import1.Layout(this.parentInjector.get(import9.ApiService),this.parentInjector.get(import10.EventService));
    this._appEl_0.initComponent(this._Layout_0_4,[],compView_0);
    compView_0.create(this._Layout_0_4,this.projectableNodes,null);
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.Layout) && (0 === requestNodeIndex))) { return this._Layout_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._Layout_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Layout_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_Layout_Host === null)) { (renderType_Layout_Host = viewUtils.createRenderComponentType('',0,null,[],{})); }
  return new _View_Layout_Host0(viewUtils,parentInjector,declarationEl);
}
export const LayoutNgFactory:import11.ComponentFactory<import1.Layout> = new import11.ComponentFactory<import1.Layout>('layout',viewFactory_Layout_Host0,import1.Layout);
const styles_Layout:any[] = [];
const nodeDebugInfos_Layout0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],null,{}),
  new import0.StaticNodeDebugInfo([],null,{}),
  new import0.StaticNodeDebugInfo([],null,{}),
  new import0.StaticNodeDebugInfo([],null,{}),
  new import0.StaticNodeDebugInfo([import12.RouterOutlet],null,{}),
  new import0.StaticNodeDebugInfo([],null,{}),
  new import0.StaticNodeDebugInfo([],null,{}),
  new import0.StaticNodeDebugInfo([],null,{})
]
;
var renderType_Layout:import2.RenderComponentType = null;
class _View_Layout0 extends import3.DebugAppView<import1.Layout> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  private _appEl_4:import4.AppElement;
  _RouterOutlet_4_5:import12.RouterOutlet;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_Layout0,renderType_Layout,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_Layout0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'main',this.debug(0,0,0));
    this.renderer.setElementAttribute(this._el_0,'class','main');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',this.debug(1,0,19));
    this._el_2 = this.renderer.createElement(this._el_0,'section',this.debug(2,1,2));
    this.renderer.setElementAttribute(this._el_2,'class','content');
    this._text_3 = this.renderer.createText(this._el_2,'\n    ',this.debug(3,1,27));
    this._el_4 = this.renderer.createElement(this._el_2,'router-outlet',this.debug(4,2,4));
    this._appEl_4 = new import4.AppElement(4,2,this,this._el_4);
    this._RouterOutlet_4_5 = new import12.RouterOutlet(this.parentInjector.get(import13.RouterOutletMap),this._appEl_4.vcRef,this.parentInjector.get(import14.ComponentFactoryResolver),null);
    this._text_5 = this.renderer.createText(this._el_2,'\n  ',this.debug(5,2,35));
    this._text_6 = this.renderer.createText(this._el_0,'\n',this.debug(6,3,12));
    this._text_7 = this.renderer.createText(parentRenderNode,'\n',this.debug(7,4,7));
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7
    ]
    ,[],[]);
    return null;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.RouterOutlet) && (4 === requestNodeIndex))) { return this._RouterOutlet_4_5; }
    return notFoundResult;
  }
  destroyInternal():void {
    this.debug(4,2,4);
    this._RouterOutlet_4_5.ngOnDestroy();
  }
}
export function viewFactory_Layout0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.Layout> {
  if ((renderType_Layout === null)) { (renderType_Layout = viewUtils.createRenderComponentType('/mnt/c/Users/asqwrd/Documents/GitHub/tv2/app/layout/layout.html',0,import15.ViewEncapsulation.None,styles_Layout,{})); }
  return new _View_Layout0(viewUtils,parentInjector,declarationEl);
}