/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/index';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/router/src/router_module';
import * as import6 from '@angular/forms/src/directives';
import * as import7 from '@angular/forms/src/form_providers';
import * as import8 from '@angular/http/http';
import * as import9 from '@angular/core/src/application_init';
import * as import10 from '@angular/core/src/testability/testability';
import * as import11 from '@angular/core/src/application_ref';
import * as import12 from '@angular/core/src/linker/compiler';
import * as import13 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import14 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import15 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import16 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import17 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import18 from '@angular/core/src/linker/view_utils';
import * as import19 from '@angular/core/src/linker/dynamic_component_loader';
import * as import20 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import21 from '@angular/http/src/backends/browser_xhr';
import * as import22 from '@angular/http/src/base_response_options';
import * as import23 from '@angular/http/src/backends/xhr_backend';
import * as import24 from '@angular/http/src/base_request_options';
import * as import25 from '@angular/common/src/location/location';
import * as import26 from '@angular/router/src/url_tree';
import * as import27 from '@angular/router/src/router_outlet_map';
import * as import28 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import29 from './services/event-services';
import * as import30 from './services/api-service';
import * as import31 from '@angular/core/src/di/injector';
import * as import32 from './layout/layout.ngfactory';
import * as import33 from './pages/guide/guide.ngfactory';
import * as import34 from './app.ngfactory';
import * as import35 from '@angular/core/src/application_tokens';
import * as import36 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import37 from '@angular/platform-browser/src/dom/events/key_events';
import * as import38 from '@angular/core/src/zone/ng_zone';
import * as import39 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import40 from '@angular/common/src/location/platform_location';
import * as import41 from '@angular/common/src/location/location_strategy';
import * as import42 from './layout/layout';
import * as import43 from './pages/guide/guide';
import * as import44 from '@angular/router/src/common_router_providers';
import * as import45 from '@angular/core/src/console';
import * as import46 from '@angular/core/src/facade/exception_handler';
import * as import47 from '@angular/core/src/linker/component_resolver';
import * as import48 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import49 from '@angular/platform-browser/src/dom/animation_driver';
import * as import50 from '@angular/core/src/render/api';
import * as import51 from '@angular/core/src/security';
import * as import52 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import53 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import54 from '@angular/http/src/interfaces';
import * as import55 from '@angular/http/src/http';
import * as import56 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import57 from '@angular/router/src/router_config_loader';
import * as import58 from '@angular/router/src/router';
import * as import59 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _RouterModule_3:import5.RouterModule;
  _InternalFormsSharedModule_4:import6.InternalFormsSharedModule;
  _FormsModule_5:import7.FormsModule;
  _HttpModule_6:import8.HttpModule;
  _AppModule_7:import1.AppModule;
  _ExceptionHandler_8:any;
  _ApplicationInitStatus_9:import9.ApplicationInitStatus;
  _Testability_10:import10.Testability;
  _ApplicationRef__11:import11.ApplicationRef_;
  __ApplicationRef_12:any;
  __Compiler_13:import12.Compiler;
  __ComponentResolver_14:any;
  __APP_ID_15:any;
  __DOCUMENT_16:any;
  __HAMMER_GESTURE_CONFIG_17:import13.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_18:any[];
  __EventManager_19:import14.EventManager;
  __DomSharedStylesHost_20:import15.DomSharedStylesHost;
  __AnimationDriver_21:any;
  __DomRootRenderer_22:import16.DomRootRenderer_;
  __RootRenderer_23:any;
  __DomSanitizationService_24:import17.DomSanitizationServiceImpl;
  __SanitizationService_25:any;
  __ViewUtils_26:import18.ViewUtils;
  __IterableDiffers_27:any;
  __KeyValueDiffers_28:any;
  __DynamicComponentLoader_29:import19.DynamicComponentLoader_;
  __SharedStylesHost_30:any;
  __RadioControlRegistry_31:import20.RadioControlRegistry;
  __BrowserXhr_32:import21.BrowserXhr;
  __ResponseOptions_33:import22.BaseResponseOptions;
  __XSRFStrategy_34:any;
  __XHRBackend_35:import23.XHRBackend;
  __RequestOptions_36:import24.BaseRequestOptions;
  __Http_37:any;
  __ROUTER_CONFIGURATION_38:any;
  __LocationStrategy_39:any;
  __Location_40:import25.Location;
  __UrlSerializer_41:import26.DefaultUrlSerializer;
  __RouterOutletMap_42:import27.RouterOutletMap;
  __NgModuleFactoryLoader_43:import28.SystemJsNgModuleLoader;
  __ROUTES_44:any[];
  __Router_45:any;
  __ActivatedRoute_46:any;
  __APP_BOOTSTRAP_LISTENER_47:any[];
  __EventService_48:import29.EventService;
  __ApiService_49:import30.ApiService;
  constructor(parent:import31.Injector) {
    super(parent,[
      import32.LayoutNgFactory,
      import33.GuideNgFactory,
      import34.AppNgFactory
    ]
    ,[import34.AppNgFactory]);
  }
  get _ApplicationRef_12():any {
    if ((this.__ApplicationRef_12 == null)) { (this.__ApplicationRef_12 = this._ApplicationRef__11); }
    return this.__ApplicationRef_12;
  }
  get _Compiler_13():import12.Compiler {
    if ((this.__Compiler_13 == null)) { (this.__Compiler_13 = new import12.Compiler()); }
    return this.__Compiler_13;
  }
  get _ComponentResolver_14():any {
    if ((this.__ComponentResolver_14 == null)) { (this.__ComponentResolver_14 = this._Compiler_13); }
    return this.__ComponentResolver_14;
  }
  get _APP_ID_15():any {
    if ((this.__APP_ID_15 == null)) { (this.__APP_ID_15 = import35._appIdRandomProviderFactory()); }
    return this.__APP_ID_15;
  }
  get _DOCUMENT_16():any {
    if ((this.__DOCUMENT_16 == null)) { (this.__DOCUMENT_16 = import4._document()); }
    return this.__DOCUMENT_16;
  }
  get _HAMMER_GESTURE_CONFIG_17():import13.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_17 == null)) { (this.__HAMMER_GESTURE_CONFIG_17 = new import13.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_17;
  }
  get _EVENT_MANAGER_PLUGINS_18():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_18 == null)) { (this.__EVENT_MANAGER_PLUGINS_18 = [
      new import36.DomEventsPlugin(),
      new import37.KeyEventsPlugin(),
      new import13.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_17)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_18;
  }
  get _EventManager_19():import14.EventManager {
    if ((this.__EventManager_19 == null)) { (this.__EventManager_19 = new import14.EventManager(this._EVENT_MANAGER_PLUGINS_18,this.parent.get(import38.NgZone))); }
    return this.__EventManager_19;
  }
  get _DomSharedStylesHost_20():import15.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_20 == null)) { (this.__DomSharedStylesHost_20 = new import15.DomSharedStylesHost(this._DOCUMENT_16)); }
    return this.__DomSharedStylesHost_20;
  }
  get _AnimationDriver_21():any {
    if ((this.__AnimationDriver_21 == null)) { (this.__AnimationDriver_21 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_21;
  }
  get _DomRootRenderer_22():import16.DomRootRenderer_ {
    if ((this.__DomRootRenderer_22 == null)) { (this.__DomRootRenderer_22 = new import16.DomRootRenderer_(this._DOCUMENT_16,this._EventManager_19,this._DomSharedStylesHost_20,this._AnimationDriver_21)); }
    return this.__DomRootRenderer_22;
  }
  get _RootRenderer_23():any {
    if ((this.__RootRenderer_23 == null)) { (this.__RootRenderer_23 = import39._createConditionalRootRenderer(this._DomRootRenderer_22)); }
    return this.__RootRenderer_23;
  }
  get _DomSanitizationService_24():import17.DomSanitizationServiceImpl {
    if ((this.__DomSanitizationService_24 == null)) { (this.__DomSanitizationService_24 = new import17.DomSanitizationServiceImpl()); }
    return this.__DomSanitizationService_24;
  }
  get _SanitizationService_25():any {
    if ((this.__SanitizationService_25 == null)) { (this.__SanitizationService_25 = this._DomSanitizationService_24); }
    return this.__SanitizationService_25;
  }
  get _ViewUtils_26():import18.ViewUtils {
    if ((this.__ViewUtils_26 == null)) { (this.__ViewUtils_26 = new import18.ViewUtils(this._RootRenderer_23,this._APP_ID_15,this._SanitizationService_25)); }
    return this.__ViewUtils_26;
  }
  get _IterableDiffers_27():any {
    if ((this.__IterableDiffers_27 == null)) { (this.__IterableDiffers_27 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_27;
  }
  get _KeyValueDiffers_28():any {
    if ((this.__KeyValueDiffers_28 == null)) { (this.__KeyValueDiffers_28 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_28;
  }
  get _DynamicComponentLoader_29():import19.DynamicComponentLoader_ {
    if ((this.__DynamicComponentLoader_29 == null)) { (this.__DynamicComponentLoader_29 = new import19.DynamicComponentLoader_(this._Compiler_13)); }
    return this.__DynamicComponentLoader_29;
  }
  get _SharedStylesHost_30():any {
    if ((this.__SharedStylesHost_30 == null)) { (this.__SharedStylesHost_30 = this._DomSharedStylesHost_20); }
    return this.__SharedStylesHost_30;
  }
  get _RadioControlRegistry_31():import20.RadioControlRegistry {
    if ((this.__RadioControlRegistry_31 == null)) { (this.__RadioControlRegistry_31 = new import20.RadioControlRegistry()); }
    return this.__RadioControlRegistry_31;
  }
  get _BrowserXhr_32():import21.BrowserXhr {
    if ((this.__BrowserXhr_32 == null)) { (this.__BrowserXhr_32 = new import21.BrowserXhr()); }
    return this.__BrowserXhr_32;
  }
  get _ResponseOptions_33():import22.BaseResponseOptions {
    if ((this.__ResponseOptions_33 == null)) { (this.__ResponseOptions_33 = new import22.BaseResponseOptions()); }
    return this.__ResponseOptions_33;
  }
  get _XSRFStrategy_34():any {
    if ((this.__XSRFStrategy_34 == null)) { (this.__XSRFStrategy_34 = import8._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_34;
  }
  get _XHRBackend_35():import23.XHRBackend {
    if ((this.__XHRBackend_35 == null)) { (this.__XHRBackend_35 = new import23.XHRBackend(this._BrowserXhr_32,this._ResponseOptions_33,this._XSRFStrategy_34)); }
    return this.__XHRBackend_35;
  }
  get _RequestOptions_36():import24.BaseRequestOptions {
    if ((this.__RequestOptions_36 == null)) { (this.__RequestOptions_36 = new import24.BaseRequestOptions()); }
    return this.__RequestOptions_36;
  }
  get _Http_37():any {
    if ((this.__Http_37 == null)) { (this.__Http_37 = import8.httpFactory(this._XHRBackend_35,this._RequestOptions_36)); }
    return this.__Http_37;
  }
  get _ROUTER_CONFIGURATION_38():any {
    if ((this.__ROUTER_CONFIGURATION_38 == null)) { (this.__ROUTER_CONFIGURATION_38 = {'useHash': true}); }
    return this.__ROUTER_CONFIGURATION_38;
  }
  get _LocationStrategy_39():any {
    if ((this.__LocationStrategy_39 == null)) { (this.__LocationStrategy_39 = import5.provideLocationStrategy(this.parent.get(import40.PlatformLocation),this.parent.get(import41.APP_BASE_HREF,null),this._ROUTER_CONFIGURATION_38)); }
    return this.__LocationStrategy_39;
  }
  get _Location_40():import25.Location {
    if ((this.__Location_40 == null)) { (this.__Location_40 = new import25.Location(this._LocationStrategy_39)); }
    return this.__Location_40;
  }
  get _UrlSerializer_41():import26.DefaultUrlSerializer {
    if ((this.__UrlSerializer_41 == null)) { (this.__UrlSerializer_41 = new import26.DefaultUrlSerializer()); }
    return this.__UrlSerializer_41;
  }
  get _RouterOutletMap_42():import27.RouterOutletMap {
    if ((this.__RouterOutletMap_42 == null)) { (this.__RouterOutletMap_42 = new import27.RouterOutletMap()); }
    return this.__RouterOutletMap_42;
  }
  get _NgModuleFactoryLoader_43():import28.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_43 == null)) { (this.__NgModuleFactoryLoader_43 = new import28.SystemJsNgModuleLoader(this._Compiler_13)); }
    return this.__NgModuleFactoryLoader_43;
  }
  get _ROUTES_44():any[] {
        if ((this.__ROUTES_44 == null)) { (this.__ROUTES_44 = [[{
          'path': '',
          'component': import42.Layout,
            'children': [{
              'path': 'guide',
              'component': import43.Guide
            }
          ]
        }
    ]]); }
    return this.__ROUTES_44;
  }
  get _Router_45():any {
    if ((this.__Router_45 == null)) { (this.__Router_45 = import44.setupRouter(this._ApplicationRef_12,this._ComponentResolver_14,this._UrlSerializer_41,this._RouterOutletMap_42,this._Location_40,this,this._NgModuleFactoryLoader_43,this._ROUTES_44,this._ROUTER_CONFIGURATION_38)); }
    return this.__Router_45;
  }
  get _ActivatedRoute_46():any {
    if ((this.__ActivatedRoute_46 == null)) { (this.__ActivatedRoute_46 = import44.rootRoute(this._Router_45)); }
    return this.__ActivatedRoute_46;
  }
  get _APP_BOOTSTRAP_LISTENER_47():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_47 == null)) { (this.__APP_BOOTSTRAP_LISTENER_47 = [import44.initialRouterNavigation(this._Router_45)]); }
    return this.__APP_BOOTSTRAP_LISTENER_47;
  }
  get _EventService_48():import29.EventService {
    if ((this.__EventService_48 == null)) { (this.__EventService_48 = new import29.EventService()); }
    return this.__EventService_48;
  }
  get _ApiService_49():import30.ApiService {
    if ((this.__ApiService_49 == null)) { (this.__ApiService_49 = new import30.ApiService(this._Http_37,this._EventService_48)); }
    return this.__ApiService_49;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule();
    this._RouterModule_3 = new import5.RouterModule();
    this._InternalFormsSharedModule_4 = new import6.InternalFormsSharedModule();
    this._FormsModule_5 = new import7.FormsModule();
    this._HttpModule_6 = new import8.HttpModule();
    this._AppModule_7 = new import1.AppModule();
    this._ExceptionHandler_8 = import4._exceptionHandler();
    this._ApplicationInitStatus_9 = new import9.ApplicationInitStatus(this.parent.get(import9.APP_INITIALIZER,null));
    this._Testability_10 = new import10.Testability(this.parent.get(import38.NgZone));
    this._ApplicationRef__11 = new import11.ApplicationRef_(this.parent.get(import38.NgZone),this.parent.get(import45.Console),this,this._ExceptionHandler_8,this,this._ApplicationInitStatus_9,this.parent.get(import10.TestabilityRegistry,null),this._Testability_10);
    return this._AppModule_7;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.RouterModule)) { return this._RouterModule_3; }
    if ((token === import6.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_4; }
    if ((token === import7.FormsModule)) { return this._FormsModule_5; }
    if ((token === import8.HttpModule)) { return this._HttpModule_6; }
    if ((token === import1.AppModule)) { return this._AppModule_7; }
    if ((token === import46.ExceptionHandler)) { return this._ExceptionHandler_8; }
    if ((token === import9.ApplicationInitStatus)) { return this._ApplicationInitStatus_9; }
    if ((token === import10.Testability)) { return this._Testability_10; }
    if ((token === import11.ApplicationRef_)) { return this._ApplicationRef__11; }
    if ((token === import11.ApplicationRef)) { return this._ApplicationRef_12; }
    if ((token === import12.Compiler)) { return this._Compiler_13; }
    if ((token === import47.ComponentResolver)) { return this._ComponentResolver_14; }
    if ((token === import35.APP_ID)) { return this._APP_ID_15; }
    if ((token === import48.DOCUMENT)) { return this._DOCUMENT_16; }
    if ((token === import13.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_17; }
    if ((token === import14.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_18; }
    if ((token === import14.EventManager)) { return this._EventManager_19; }
    if ((token === import15.DomSharedStylesHost)) { return this._DomSharedStylesHost_20; }
    if ((token === import49.AnimationDriver)) { return this._AnimationDriver_21; }
    if ((token === import16.DomRootRenderer)) { return this._DomRootRenderer_22; }
    if ((token === import50.RootRenderer)) { return this._RootRenderer_23; }
    if ((token === import17.DomSanitizationService)) { return this._DomSanitizationService_24; }
    if ((token === import51.SanitizationService)) { return this._SanitizationService_25; }
    if ((token === import18.ViewUtils)) { return this._ViewUtils_26; }
    if ((token === import52.IterableDiffers)) { return this._IterableDiffers_27; }
    if ((token === import53.KeyValueDiffers)) { return this._KeyValueDiffers_28; }
    if ((token === import19.DynamicComponentLoader)) { return this._DynamicComponentLoader_29; }
    if ((token === import15.SharedStylesHost)) { return this._SharedStylesHost_30; }
    if ((token === import20.RadioControlRegistry)) { return this._RadioControlRegistry_31; }
    if ((token === import21.BrowserXhr)) { return this._BrowserXhr_32; }
    if ((token === import22.ResponseOptions)) { return this._ResponseOptions_33; }
    if ((token === import54.XSRFStrategy)) { return this._XSRFStrategy_34; }
    if ((token === import23.XHRBackend)) { return this._XHRBackend_35; }
    if ((token === import24.RequestOptions)) { return this._RequestOptions_36; }
    if ((token === import55.Http)) { return this._Http_37; }
    if ((token === import44.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_38; }
    if ((token === import41.LocationStrategy)) { return this._LocationStrategy_39; }
    if ((token === import25.Location)) { return this._Location_40; }
    if ((token === import26.UrlSerializer)) { return this._UrlSerializer_41; }
    if ((token === import27.RouterOutletMap)) { return this._RouterOutletMap_42; }
    if ((token === import56.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_43; }
    if ((token === import57.ROUTES)) { return this._ROUTES_44; }
    if ((token === import58.Router)) { return this._Router_45; }
    if ((token === import59.ActivatedRoute)) { return this._ActivatedRoute_46; }
    if ((token === import35.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_47; }
    if ((token === import29.EventService)) { return this._EventService_48; }
    if ((token === import30.ApiService)) { return this._ApiService_49; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__11.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);